[package]
name = "crust"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.172"


[profile.dev]
panic = "abort"
opt-level = "z"

# These introduce rust_eh_personality linker errors so they should be false
debug-assertions = false
overflow-checks = false

[profile.release]
panic = "abort"
opt-level = "z"
